#!/usr/bin/env python3
"""
Inject a "suburbs we service" internal link block into every service page.

Why this exists
---------------
SEO audit 2026-08-16, finding F7: the 18 service pages carried zero links to
the 31 suburb pages, so there was no internal path routing crawl budget to
them. Google reported 110 URLs at "Discovered, currently not indexed".

This is the single source of truth for the service area shown on service
pages. When Kai confirms the real service area, edit SUBURBS and re-run:

    python3 generate_service_suburb_links.py

The script is idempotent. It replaces any block it previously wrote, so it is
safe to run repeatedly.
"""

import glob
import html
import re
import sys

# ---------------------------------------------------------------------------
# The service area. Matches llms.txt and /suburbs/ as at 2026-08-17.
# Inner north (11), inner south (8), Woden Valley (12).
# ---------------------------------------------------------------------------
SUBURBS = [
    ("ainslie", "Ainslie"), ("barton", "Barton"), ("braddon", "Braddon"),
    ("campbell", "Campbell"), ("chifley", "Chifley"), ("curtin", "Curtin"),
    ("deakin", "Deakin"), ("dickson", "Dickson"), ("downer", "Downer"),
    ("farrer", "Farrer"), ("forrest", "Forrest"), ("garran", "Garran"),
    ("griffith", "Griffith"), ("hackett", "Hackett"), ("hughes", "Hughes"),
    ("isaacs", "Isaacs"), ("kingston", "Kingston"), ("lyneham", "Lyneham"),
    ("lyons", "Lyons"), ("mawson", "Mawson"), ("narrabundah", "Narrabundah"),
    ("oconnor", "O'Connor"), ("omalley", "O'Malley"), ("pearce", "Pearce"),
    ("phillip", "Phillip"), ("red-hill", "Red Hill"), ("reid", "Reid"),
    ("torrens", "Torrens"), ("turner", "Turner"), ("watson", "Watson"),
    ("yarralumla", "Yarralumla"),
]

AREA_SUMMARY = "Canberra's inner north, inner south and Woden Valley"

BEGIN = "<!-- Suburbs we service: BEGIN generated by generate_service_suburb_links.py -->"
END = "<!-- Suburbs we service: END generated -->"

ANCHOR = "<!-- Final CTA -->"


def service_name(source: str) -> str:
    """Pull the service name from the BreadcrumbList, sentence-cased."""
    match = re.search(r'"position":\s*3,\s*"name":\s*"([^"]+)"', source)
    if not match:
        return ""
    name = html.unescape(match.group(1)).replace("&", "and")
    name = re.sub(r"\s+", " ", name).strip().lower()
    return name[:1].upper() + name[1:]


def build_block(name: str) -> str:
    heading = f"{name} across Canberra, suburb by suburb." if name \
        else "Where Kai works, suburb by suburb."
    links = "\n".join(
        f'        <a href="/suburbs/{slug}/">{label}</a>'
        for slug, label in SUBURBS
    )
    return f"""{BEGIN}
<section class="section section--cream" aria-labelledby="suburbs-heading">
  <div class="container-narrow">
    <span class="eyebrow">Where we work</span>
    <h2 id="suburbs-heading">{heading}</h2>
    <p>Kai works out of Hackett and covers {len(SUBURBS)} suburbs across {AREA_SUMMARY}. Pick your suburb for the local detail, or just call and ask.</p>
    <nav class="nearby" aria-label="Suburbs we service">
{links}
        <a href="/suburbs/">All suburbs</a>
    </nav>
  </div>
</section>

{END}

"""


def process(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        source = handle.read()

    # Remove a previously generated block so re-runs stay clean.
    source = re.sub(
        re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n*",
        "",
        source,
        flags=re.S,
    )

    if ANCHOR not in source:
        return "SKIPPED (no Final CTA anchor)"

    block = build_block(service_name(source))
    updated = source.replace(ANCHOR, block + ANCHOR, 1)

    with open(path, "w", encoding="utf-8") as handle:
        handle.write(updated)
    return f"OK ({len(SUBURBS)} suburb links)"


def main() -> int:
    pages = sorted(glob.glob("services/*/index.html"))
    if not pages:
        print("No service pages found. Run from the repo root.", file=sys.stderr)
        return 1
    for path in pages:
        print(f"{path:46s} {process(path)}")
    print(f"\n{len(pages)} service pages processed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
